// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIL2WA4OFg75TovqD271hj9IZLSqmzxBM',
    appId: '1:492575920149:android:5937a6c4ac866da61ebe1c',
    messagingSenderId: '492575920149',
    projectId: 'mekina-parking',
    databaseURL: 'https://mekina-parking-default-rtdb.firebaseio.com',
    storageBucket: 'mekina-parking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEcSjtOjN-VcO0c_CgQhCD6fj44S6aIAk',
    appId: '1:492575920149:ios:4506e4cd337ad5b31ebe1c',
    messagingSenderId: '492575920149',
    projectId: 'mekina-parking',
    databaseURL: 'https://mekina-parking-default-rtdb.firebaseio.com',
    storageBucket: 'mekina-parking.firebasestorage.app',
    iosClientId: '492575920149-k8ifvs1l714vrknevqlp9vi56auiicmj.apps.googleusercontent.com',
    iosBundleId: 'com.mekinaparking.owner',
  );

}